language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  review_status: true
  poem: true
  collapse_walkthrough: false
  sequence_diagrams: true
  path_filters: [
    "!**/*.ptxt"
  ]
  path_instructions: [
    {
      "path": "docs/*.md",
      "instructions": "Review for clarity, grammar, and alignment with educational gamification. Suggest improvements for user guides or technical docs."
    },
    {
      "path": "*.php",
      "instructions": "Check for security (e.g., prepared statements, CSRF), performance, and PHP best practices. Propose optimizations for backend logic like user tracking."
    },
    {
      "path": "*.js",
      "instructions": "Ensure JS code is efficient, handles errors, and integrates well with libraries like Three.js or Chart.js. Suggest enhancements for interactivity."
    }
  ]
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  tools:
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      level: default
    biome:
      enabled: true
    phpstan:
      enabled: true
      level: default
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    eslint:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
